  <main role="main">    <h1>Class AuthenticationException</h1>   <ul class="inheritance"> <li><a href="../../../../java.base/java/lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../../../../java.base/java/lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../../../../java.base/java/lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li><a href="../../../../java.base/java/io/ioexception">java.io.IOException</a></li> <li> <ul class="inheritance"> <li><a href="saslexception">javax.security.sasl.SaslException</a></li> <li> <ul class="inheritance"> <li>javax.security.sasl.AuthenticationException</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><code><a href="../../../../java.base/java/io/serializable">Serializable</a></code></dd> </dl>  <pre data-language="java">public class AuthenticationException
extends SaslException</pre> <div>
<p>This exception is thrown by a SASL mechanism implementation to indicate that the SASL exchange has failed due to reasons related to authentication, such as an invalid identity, passphrase, or key. </p>
<p> Note that the lack of an AuthenticationException does not mean that the failure was not due to an authentication error. A SASL mechanism implementation might throw the more general SaslException instead of AuthenticationException if it is unable to determine the nature of the failure, or if does not want to disclose the nature of the failure, for example, due to security reasons.</p>
</div> <dl> <dt>Since:</dt> <dd>1.5</dd> <dt>See Also:</dt> <dd><a href="https://docs.oracle.com/en/java/javase/11/docs/api/serialized-form.html#javax.security.sasl.AuthenticationException">Serialized Form</a></dd> </dl>      <section role="region">  <h2 id="constructor.summary">Constructors</h2> <table>  <tr> <th scope="col">Constructor</th> <th scope="col">Description</th> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E()">AuthenticationException</a>()</code></th> <td> <p>Constructs a new instance of <code>AuthenticationException</code>.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String)">AuthenticationException</a>​(<a href="../../../../java.base/java/lang/string">String</a> detail)</code></th> <td> <p>Constructs a new instance of <code>AuthenticationException</code> with a detailed message.</p> </td> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.String,java.lang.Throwable)">AuthenticationException</a>​(<a href="../../../../java.base/java/lang/string">String</a> detail,
                       <a href="../../../../java.base/java/lang/throwable">Throwable</a> ex)</code></th> <td> <p>Constructs a new instance of <code>AuthenticationException</code> with a detailed message and a root exception.</p> </td> </tr> </table>  </section>  <section role="region">  <h2 id="method.summary">Methods</h2>  <h2 id="methods.inherited.from.class.javax.security.sasl.SaslException">Methods declared in class javax.security.sasl.<a href="saslexception">SaslException</a>
</h2> <code><a href="saslexception#toString()">toString</a></code>  <h2 id="methods.inherited.from.class.java.lang.Throwable">Methods declared in class java.lang.<a href="../../../../java.base/java/lang/throwable">Throwable</a>
</h2> <code><a href="../../../../java.base/java/lang/throwable#addSuppressed(java.lang.Throwable)">addSuppressed</a>, <a href="../../../../java.base/java/lang/throwable#fillInStackTrace()">fillInStackTrace</a>, <a href="../../../../java.base/java/lang/throwable#getCause()">getCause</a>, <a href="../../../../java.base/java/lang/throwable#getLocalizedMessage()">getLocalizedMessage</a>, <a href="../../../../java.base/java/lang/throwable#getMessage()">getMessage</a>, <a href="../../../../java.base/java/lang/throwable#getStackTrace()">getStackTrace</a>, <a href="../../../../java.base/java/lang/throwable#getSuppressed()">getSuppressed</a>, <a href="../../../../java.base/java/lang/throwable#initCause(java.lang.Throwable)">initCause</a>, <a href="../../../../java.base/java/lang/throwable#printStackTrace()">printStackTrace</a>, <a href="../../../../java.base/java/lang/throwable#printStackTrace(java.io.PrintStream)">printStackTrace</a>, <a href="../../../../java.base/java/lang/throwable#printStackTrace(java.io.PrintWriter)">printStackTrace</a>, <a href="../../../../java.base/java/lang/throwable#setStackTrace(java.lang.StackTraceElement%5B%5D)">setStackTrace</a></code>  <h2 id="methods.inherited.from.class.java.lang.Object">Methods declared in class java.lang.<a href="../../../../java.base/java/lang/object">Object</a>
</h2> <code><a href="../../../../java.base/java/lang/object#clone()">clone</a>, <a href="../../../../java.base/java/lang/object#equals(java.lang.Object)">equals</a>, <a href="../../../../java.base/java/lang/object#finalize()">finalize</a>, <a href="../../../../java.base/java/lang/object#getClass()">getClass</a>, <a href="../../../../java.base/java/lang/object#hashCode()">hashCode</a>, <a href="../../../../java.base/java/lang/object#notify()">notify</a>, <a href="../../../../java.base/java/lang/object#notifyAll()">notifyAll</a>, <a href="../../../../java.base/java/lang/object#wait()">wait</a>, <a href="../../../../java.base/java/lang/object#wait(long)">wait</a>, <a href="../../../../java.base/java/lang/object#wait(long,int)">wait</a></code>  </section>   <div>   <section role="region">  <h2 id="constructor.detail">Constructors</h2>   <h3 id="&lt;init&gt;()">AuthenticationException</h3> <pre data-language="java">public AuthenticationException()</pre> <p>Constructs a new instance of <code>AuthenticationException</code>. The root exception and the detailed message are null.</p>    <h3 id="&lt;init&gt;(java.lang.String)">AuthenticationException</h3> <pre data-language="java">public AuthenticationException(String detail)</pre> <p>Constructs a new instance of <code>AuthenticationException</code> with a detailed message. The root exception is null.</p> <dl> <dt>Parameters:</dt> <dd>
<code>detail</code> - A possibly null string containing details of the exception.</dd> <dt>See Also:</dt> <dd><a href="../../../../java.base/java/lang/throwable#getMessage()"><code>Throwable.getMessage()</code></a></dd> </dl>    <h3 id="&lt;init&gt;(java.lang.String,java.lang.Throwable)">AuthenticationException</h3> <pre data-language="java">public AuthenticationException(String detail,
                               Throwable ex)</pre> <p>Constructs a new instance of <code>AuthenticationException</code> with a detailed message and a root exception.</p> <dl> <dt>Parameters:</dt> <dd>
<code>detail</code> - A possibly null string containing details of the exception.</dd> <dd>
<code>ex</code> - A possibly null root exception that caused this exception.</dd> <dt>See Also:</dt> <dd>
<a href="../../../../java.base/java/lang/throwable#getMessage()"><code>Throwable.getMessage()</code></a>, <a href="../../../../java.base/java/lang/throwable#getCause()"><code>Throwable.getCause()</code></a>
</dd> </dl>   </section>  </div>  </main>  <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993, 2020, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.security.sasl/javax/security/sasl/AuthenticationException.html" class="_attribution-link">https://docs.oracle.com/en/java/javase/11/docs/api/java.security.sasl/javax/security/sasl/AuthenticationException.html</a>
  </p>
</div>
